apiVersion: apps/v1
kind: Deployment
metadata:
    name: survey-ui-$ENVIRONMENT
    namespace: $ENVIRONMENT
    labels:
        app: survey-ui-$ENVIRONMENT
spec:
    replicas: 1
    selector:
        matchLabels:
            app: survey-ui-$ENVIRONMENT
    template:
        metadata:
            labels:
                app: survey-ui-$ENVIRONMENT
        spec:
            containers:
                - name: survey-ui-$ENVIRONMENT
                  image: image ON EKS-ui:$ENVIRONMENT-latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: survey-ui-$ENVIRONMENT
    namespace: $ENVIRONMENT
spec:
    ports:
        - name: survey-ui
          port: 83
          targetPort: 80
          protocol: TCP
    type: NodePort
    selector:
        app: survey-ui-$ENVIRONMENT
